/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.WindowListener;

/**
 *
 * @author juangocc
 */
public class JFConnecciones extends javax.swing.JFrame {

    /**
     * Creates new form JFConnecciones
     */
//PuertoSerialJSSC portjssc;
//PuertoSerialRXTX portrxtx;
    public JFConnecciones() {
        initComponents();
//        portjssc = new PuertoSerialJSSC();
//        portrxtx = new PuertoSerialRXTX();
    }

    public void setSubscriptionEvents(ActionListener al, KeyListener kl, WindowListener wl) {
        jBConectarRXTX1.addActionListener(al);
        jBDesconectarRXTX1.addActionListener(al);

        jBConectarRXTX2.addActionListener(al);
        jBDesconectarRXTX2.addActionListener(al);

        jBActualizar.addActionListener(al);
        //------------------------------------
        jTARXTX1Read.addKeyListener(kl);
        jTARXTX1Write.addKeyListener(kl);

        jTARXTX2Read.addKeyListener(kl);
        jTARXTX2Write.addKeyListener(kl);
        //-------------------------------------------
        this.addWindowListener(wl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLRXTX1 = new javax.swing.JLabel();
        jLRXTX2 = new javax.swing.JLabel();
        jBConectarRXTX1 = new javax.swing.JButton();
        jBConectarRXTX2 = new javax.swing.JButton();
        jBDesconectarRXTX1 = new javax.swing.JButton();
        jBDesconectarRXTX2 = new javax.swing.JButton();
        jCBPortsRXTX1 = new javax.swing.JComboBox();
        jCBPortsRXTX2 = new javax.swing.JComboBox();
        jLPD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTARXTX1Read = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTARXTX2Read = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTARXTX1Write = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTARXTX2Write = new javax.swing.JTextArea();
        jBActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLRXTX1.setText("RXTX 1");

        jLRXTX2.setText("RXTX 2");

        jBConectarRXTX1.setText("Conectar");
        jBConectarRXTX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarRXTX1ActionPerformed(evt);
            }
        });

        jBConectarRXTX2.setText("Conectar");
        jBConectarRXTX2.setName("jBConectarRXTX2"); // NOI18N
        jBConectarRXTX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarRXTX2ActionPerformed(evt);
            }
        });

        jBDesconectarRXTX1.setText("Desconectar");
        jBDesconectarRXTX1.setEnabled(false);
        jBDesconectarRXTX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesconectarRXTX1ActionPerformed(evt);
            }
        });

        jBDesconectarRXTX2.setText("Desconectar");
        jBDesconectarRXTX2.setEnabled(false);
        jBDesconectarRXTX2.setName("jBDesconectarRXTX2"); // NOI18N
        jBDesconectarRXTX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesconectarRXTX2ActionPerformed(evt);
            }
        });

        jCBPortsRXTX1.setEditable(true);
        jCBPortsRXTX1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM0" }));

        jCBPortsRXTX2.setEditable(true);
        jCBPortsRXTX2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1" }));

        jLPD.setText("Puertos Disponibles");

        jTARXTX1Read.setColumns(20);
        jTARXTX1Read.setRows(5);
        jScrollPane1.setViewportView(jTARXTX1Read);

        jTARXTX2Read.setColumns(20);
        jTARXTX2Read.setRows(5);
        jScrollPane2.setViewportView(jTARXTX2Read);

        jTARXTX1Write.setColumns(20);
        jTARXTX1Write.setRows(5);
        jTARXTX1Write.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTARXTX1WriteKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTARXTX1Write);

        jTARXTX2Write.setColumns(20);
        jTARXTX2Write.setRows(5);
        jTARXTX2Write.setName("jTARXTX2Write"); // NOI18N
        jTARXTX2Write.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTARXTX2WriteKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTARXTX2Write);

        jBActualizar.setText("Actualizar");
        jBActualizar.setName("jBActualizar"); // NOI18N
        jBActualizar.setOpaque(true);
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLRXTX1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLRXTX2)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBConectarRXTX1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBPortsRXTX1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDesconectarRXTX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBPortsRXTX2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBConectarRXTX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDesconectarRXTX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLPD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jBActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRXTX1)
                    .addComponent(jLRXTX2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLPD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBActualizar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPortsRXTX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPortsRXTX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConectarRXTX1)
                    .addComponent(jBConectarRXTX2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDesconectarRXTX1)
                    .addComponent(jBDesconectarRXTX2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConectarRXTX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarRXTX1ActionPerformed
    }//GEN-LAST:event_jBConectarRXTX1ActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBConectarRXTX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarRXTX2ActionPerformed
    }//GEN-LAST:event_jBConectarRXTX2ActionPerformed

    private void jTARXTX1WriteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTARXTX1WriteKeyPressed
    }//GEN-LAST:event_jTARXTX1WriteKeyPressed

    private void jTARXTX2WriteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTARXTX2WriteKeyPressed
    }//GEN-LAST:event_jTARXTX2WriteKeyPressed

    private void jBDesconectarRXTX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesconectarRXTX1ActionPerformed
    }//GEN-LAST:event_jBDesconectarRXTX1ActionPerformed

    private void jBDesconectarRXTX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesconectarRXTX2ActionPerformed
    }//GEN-LAST:event_jBDesconectarRXTX2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBConectarRXTX1;
    private javax.swing.JButton jBConectarRXTX2;
    private javax.swing.JButton jBDesconectarRXTX1;
    private javax.swing.JButton jBDesconectarRXTX2;
    private javax.swing.JComboBox jCBPortsRXTX1;
    private javax.swing.JComboBox jCBPortsRXTX2;
    private javax.swing.JLabel jLPD;
    private javax.swing.JLabel jLRXTX1;
    private javax.swing.JLabel jLRXTX2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTARXTX1Read;
    private javax.swing.JTextArea jTARXTX1Write;
    private javax.swing.JTextArea jTARXTX2Read;
    private javax.swing.JTextArea jTARXTX2Write;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jBActualizar
     */
    public javax.swing.JButton getjBActualizar() {
        return jBActualizar;
    }

    /**
     * @param jBActualizar the jBActualizar to set
     */
    public void setjBActualizar(javax.swing.JButton jBActualizar) {
        this.jBActualizar = jBActualizar;
    }

    /**
     * @return the jCBPortsRXTX
     */
    public javax.swing.JComboBox getjCBPortsRXTX2() {
        return jCBPortsRXTX2;
    }

    /**
     * @param jCBPortsRXTX the jCBPortsRXTX to set
     */
    public void setjCBPortsRXTX2(javax.swing.JComboBox jCBPortsRXTX) {
        this.jCBPortsRXTX2 = jCBPortsRXTX;
    }

    /**
     * @return the jBConectarRXTX
     */
    public javax.swing.JButton getjBConectarRXTX2() {
        return jBConectarRXTX2;
    }

    /**
     * @param jBConectarRXTX the jBConectarRXTX to set
     */
    public void setjBConectarRXTX2(javax.swing.JButton jBConectarRXTX) {
        this.jBConectarRXTX2 = jBConectarRXTX;
    }

    /**
     * @return the jBDesconectarRXTX
     */
    public javax.swing.JButton getjBDesconectarRXTX2() {
        return jBDesconectarRXTX2;
    }

    /**
     * @param jBDesconectarRXTX the jBDesconectarRXTX to set
     */
    public void setjBDesconectarRXTX2(javax.swing.JButton jBDesconectarRXTX) {
        this.jBDesconectarRXTX2 = jBDesconectarRXTX;
    }

    /**
     * @return the jTARXTXWrite
     */
    public javax.swing.JTextArea getjTARXTX2Write() {
        return jTARXTX2Write;
    }

    /**
     * @param jTARXTXWrite the jTARXTXWrite to set
     */
    public void setjTARXTX2Write(javax.swing.JTextArea jTARXTXWrite) {
        this.jTARXTX2Write = jTARXTXWrite;
    }

    /**
     * @return the jTARXTXRead
     */
    public javax.swing.JTextArea getjTARXTX2Read() {
        return jTARXTX2Read;
    }

    /**
     * @param jTARXTXRead the jTARXTXRead to set
     */
    public void setjTARXTX2Read(javax.swing.JTextArea jTARXTXRead) {
        this.jTARXTX2Read = jTARXTXRead;
    }
}
