/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.domotica.interfaz;

import com.domotica.controller.CustomDefaultTreeCellRender;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.ScrollPaneLayout;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeModel;

/**
 *
 * @author juangocc
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    jPEditorSistema jpesistema;
    jPEditorHabitacion jpehabitacion;
    jPEditorDispositivo jpedispositivo;
    
    public JFPrincipal() {
        initComponents();
        this.setTitle("Sistema Ambientes Controlados - Habitaciones");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.jScrollPaneEditar.setLayout(new ScrollPaneLayout());
        this.jTPEventos.setContentType("text/html");
        this.inicializarPanelesEditor();
        this.setVisible(true);
    }
    
    public void setSubscripcionEventos(ActionListener al) {
        jpesistema.setSubcripcionEventos(al);
        jpehabitacion.setSubcripcionEventos(al);
        jpedispositivo.setSubcripcionEventos(al);
    }
    
    private void inicializarPanelesEditor() {
        jpesistema = new jPEditorSistema();
        jpehabitacion = new jPEditorHabitacion();
        jpedispositivo = new jPEditorDispositivo();
        jScrollPaneEditar.setViewportView(jpesistema);
    }
    
    public void setDatosArbol(TreeModel nuevo_modelo, TreeSelectionListener tsl) {
        jTree1.setModel(nuevo_modelo);
        CustomDefaultTreeCellRender jtcr = new CustomDefaultTreeCellRender();
        jTree1.setCellRenderer(jtcr);
        jTree1.setSelectionRow(0);
        jTree1.addTreeSelectionListener(tsl);
    }
    
    public void setDatosSistema(String nombre, int id, String estado, int modoperacion, String descripcion) {
        jpesistema.setDatosSistema(nombre, id, estado, modoperacion, descripcion);
        jScrollPaneEditar.setViewportView(jpesistema);
        jTPannedTab.repaint();
    }
    
    public void setDatosHabitacion( int id, String estado, String descripcion, int idsensor, int humedad, int tempref, int temp, int iluminacion, int humedadideal, int ventilacion, int iluminacionideal, boolean automatico, int tempideal, int ventilacionideal) {
        jpehabitacion.setDatosHabitacion( id, estado, descripcion, idsensor, humedad, tempref, temp, iluminacion, humedadideal, ventilacion, iluminacionideal, automatico, tempideal, ventilacionideal);
        jScrollPaneEditar.setViewportView(jpehabitacion);
        jTPannedTab.repaint();
    }
    
    public void setDatosDispositivo(String nombre, int id, String estado, int valor, String tipo, String descripcion) {
        jpedispositivo.setDatosDispositivo(nombre, id, estado, valor, tipo, descripcion);
        jScrollPaneEditar.setViewportView(jpedispositivo);
        jTPannedTab.repaint();
    }
    
    public void aderirEventos(String evento) {
        String pretxt = jTPEventos.getText();
        if (pretxt != null) {
            jTPEventos.setText(pretxt + "<br>" + evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTPannedTab = new javax.swing.JTabbedPane();
        jPPrincipal = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        jScrollPaneEditar = new javax.swing.JScrollPane();
        jPCronograma = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jPEstadisticas = new javax.swing.JPanel();
        jPEventos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPEventos = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMICargar = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        jMEditar = new javax.swing.JMenu();
        jMIBuscar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMAyuda = new javax.swing.JMenu();
        jMIAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setOneTouchExpandable(true);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(80, 54));
        jScrollPane1.setName(""); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Sistema");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Habitacion1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Habitacion2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Habitacion3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dispositivo4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTree1.setDragEnabled(true);
        jTree1.setEditable(true);
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jTPannedTab.addTab("Principal", jPPrincipal);

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPaneEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPannedTab.addTab("Editar", jPEditar);

        jScrollPane2.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Habitacion", "Dispositivo", "Estado", "Valor", "Fecha", "Hora", "Intervalo", "Periodo"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);

        jToolBar2.setRollover(true);

        javax.swing.GroupLayout jPCronogramaLayout = new javax.swing.GroupLayout(jPCronograma);
        jPCronograma.setLayout(jPCronogramaLayout);
        jPCronogramaLayout.setHorizontalGroup(
            jPCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCronogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPCronogramaLayout.setVerticalGroup(
            jPCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCronogramaLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jTPannedTab.addTab("Cronograma", jPCronograma);

        javax.swing.GroupLayout jPEstadisticasLayout = new javax.swing.GroupLayout(jPEstadisticas);
        jPEstadisticas.setLayout(jPEstadisticasLayout);
        jPEstadisticasLayout.setHorizontalGroup(
            jPEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPEstadisticasLayout.setVerticalGroup(
            jPEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jTPannedTab.addTab("Estadisticas", jPEstadisticas);

        jScrollPane3.setViewportView(jTPEventos);

        javax.swing.GroupLayout jPEventosLayout = new javax.swing.GroupLayout(jPEventos);
        jPEventos.setLayout(jPEventosLayout);
        jPEventosLayout.setHorizontalGroup(
            jPEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        jPEventosLayout.setVerticalGroup(
            jPEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEventosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPannedTab.addTab("Eventos", jPEventos);

        jSplitPane1.setRightComponent(jTPannedTab);

        jMArchivo.setText("Archivo");

        jMICargar.setText("Cargar");
        jMArchivo.add(jMICargar);

        jMIGuardar.setText("Guardar");
        jMArchivo.add(jMIGuardar);

        jMenuBar1.add(jMArchivo);

        jMEditar.setText("Editar");

        jMIBuscar.setText("Buscar");
        jMEditar.add(jMIBuscar);

        jMenuItem4.setText("jMenuItem4");
        jMEditar.add(jMenuItem4);

        jMenuBar1.add(jMEditar);

        jMAyuda.setText("Ayuda");

        jMIAcercade.setText("Acerca de");
        jMAyuda.add(jMIAcercade);

        jMenuBar1.add(jMAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenu jMAyuda;
    private javax.swing.JMenu jMEditar;
    private javax.swing.JMenuItem jMIAcercade;
    private javax.swing.JMenuItem jMIBuscar;
    private javax.swing.JMenuItem jMICargar;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPCronograma;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPEstadisticas;
    private javax.swing.JPanel jPEventos;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneEditar;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTPEventos;
    private javax.swing.JTabbedPane jTPannedTab;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
