/*
 * VentanaPruebas.java
 * Created on 25 de enero de 2009, 17:53
 */
package pruebacomunicacion;

import gnu.io.PortInUseException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pablo
 */
public class VentanaPruebas extends javax.swing.JFrame {

    PuertoSerial puerto;

    public VentanaPruebas() {
        initComponents();
        puerto = new PuertoSerial("/dev/ttyS1");
        puerto.setCajaTexto(jTextArea1);
        puerto.setCajaTexto2(jTextArea2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SelDestino = new javax.swing.JComboBox();
        jTextEstado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckC1 = new javax.swing.JCheckBox();
        selC1 = new javax.swing.JComboBox();
        selC2 = new javax.swing.JComboBox();
        jCheckC2 = new javax.swing.JCheckBox();
        jCheckE1 = new javax.swing.JCheckBox();
        selE1 = new javax.swing.JComboBox();
        selAA = new javax.swing.JComboBox();
        jCheckAA = new javax.swing.JCheckBox();
        jCheckP1 = new javax.swing.JCheckBox();
        selP1 = new javax.swing.JComboBox();
        jSlider1 = new javax.swing.JSlider();
        jCheckBX = new javax.swing.JCheckBox();
        jCheckE2 = new javax.swing.JCheckBox();
        selE2 = new javax.swing.JComboBox();
        jBEnviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SelOrigen = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("DISPOSITIVOS");

        jLabel5.setText("CABECERA DE TRAMA");

        jLabel3.setText("Estado:");

        jLabel2.setText("Dir Origen:");

        jLabel1.setText("Enviar a: ");

        SelDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "T.C.M", "Habitación 1", "Habitación 2", "Habitación 3", "T. Sensado 1", "T. Sensado 2", "T. Sensado 3" }));

        jTextEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEstadoActionPerformed(evt);
            }
        });

        jCheckC1.setText("C1");
        jCheckC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckC1ActionPerformed(evt);
            }
        });

        selC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apagado", "Medio", "Alto" }));

        selC2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apagado", "Medio", "Alto" }));
        selC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selC2ActionPerformed(evt);
            }
        });

        jCheckC2.setText("C2");
        jCheckC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckC2ActionPerformed(evt);
            }
        });

        jCheckE1.setText("E1");

        selE1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apagado", "Bajo", "Medio", "Alto" }));
        selE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selE1ActionPerformed(evt);
            }
        });

        selAA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apagado", "Medio", "Alto", "DesHumidificar" }));
        selAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAAActionPerformed(evt);
            }
        });

        jCheckAA.setText("AA");

        jCheckP1.setText("P1");

        selP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cerrado", "Bajo", "Medio", "Abiertas" }));
        selP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selP1ActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(255);
        jSlider1.setPaintLabels(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jCheckBX.setText("BX");

        jCheckE2.setText("E2");

        selE2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apagado", "Bajo", "Medio", "Alto" }));
        selE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selE2ActionPerformed(evt);
            }
        });

        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jLabel7.setText("LongDatos");

        jLabel8.setText("0");

        jLabel9.setText("50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckE1)
                                    .addComponent(jCheckC2)
                                    .addComponent(jCheckC1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(selC1, 0, 196, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selE1, 0, 196, Short.MAX_VALUE)
                                            .addComponent(selC2, 0, 196, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckE2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selE2, 0, 198, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckAA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selAA, 0, 196, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckP1)
                                .addGap(8, 8, 8)
                                .addComponent(selP1, 0, 196, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBX)
                                .addGap(0, 0, 0)
                                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jBEnviar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckC1)
                    .addComponent(selC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckC2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckE1)
                    .addComponent(selE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckE2)
                    .addComponent(selE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selAA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckAA))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckP1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jCheckBX)))))
                    .addComponent(selP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEnviar)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        SelOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "T.C.M", "Habitación 1", "Habitación 2", "Habitación 3", "T. Sensado 1", "T. Sensado 2", "T. Sensado 3" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SelOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelDestino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextEstado, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Trama Recibida");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEstadoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextEstadoActionPerformed

private void jCheckC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckC1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckC1ActionPerformed

private void selC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selC2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_selC2ActionPerformed

private void jCheckC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckC2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckC2ActionPerformed

private void selE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selE1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_selE1ActionPerformed

private void selAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAAActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_selAAActionPerformed

private void selP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selP1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_selP1ActionPerformed

private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
    int longiTotal, longDatos, contTrama;
    longiTotal = 2 + 1 + 1 + 1 + 1 + 2;
    //2 "PA", 1 Longitud, 1 Origen, 1 Destino 1 Estado 2 "MR". 
    contTrama = 0;
    longDatos = 0;

    jTextArea1.setText("");
    jTextArea2.setText("");
    if (jCheckC1.isSelected()) {
        longDatos += 3;
    }
    if (jCheckC2.isSelected()) {
        longDatos += 3;
    }
    if (jCheckE1.isSelected()) {
        longDatos += 3;
    }
    if (jCheckE2.isSelected()) {
        longDatos += 3;
    }
    if (jCheckAA.isSelected()) {
        longDatos += 3;
    }
    if (jCheckP1.isSelected()) {
        longDatos += 3;
    }
    if (jCheckBX.isSelected()) {
        longDatos += 3;
    }

    jLabel8.setText(String.valueOf(longDatos));

    longiTotal += longDatos;

    byte[] trama;
    trama = new byte[longiTotal];
    trama[0] = 'P';
    trama[1] = 'A';
    trama[2] = (byte) (longDatos & 0x000000FF); //Longitud
    trama[3] = (byte) ((SelOrigen.getSelectedIndex() + 100) & 0x000000FF);
    trama[4] = (byte) ((SelDestino.getSelectedIndex() + 100) & 0x000000FF);
    trama[5] = (byte) (Integer.parseInt(jTextEstado.getText()) & 0x000000FF);

    contTrama = 6;

    if (jCheckC1.isSelected()) {
        trama[contTrama] = 'C';
        trama[contTrama + 1] = '1';
        trama[contTrama + 2] = (byte) ((selC1.getSelectedIndex()) & 0x000000FF);
        contTrama += 3;
    }
    if (jCheckC2.isSelected()) {
        trama[contTrama] = 'C';
        trama[contTrama + 1] = '2';
        trama[contTrama + 2] = (byte) ((selC2.getSelectedIndex()) & 0x000000FF);
        contTrama += 3;
    }
    byte temp = 0;
    if (jCheckE1.isSelected()) {
        System.out.println("E1");
        trama[contTrama] = 'E';
        trama[contTrama + 1] = '1';

        switch (selE1.getSelectedIndex()) {
            //Apagado
            case 0:
                temp = 0;
                break;
            //bajo
            case 1:
                temp = 1;
                break;
            //Medio
            case 2:
                temp = 2;
                break;
            //Alto
            case 3:
                temp = 4;
                break;
        }
        trama[contTrama + 2] = (byte) ((temp) & 0x000000FF);
        contTrama += 3;
    }
    if (jCheckE2.isSelected()) {
        System.out.println("E2");
        trama[contTrama] = 'E';
        trama[contTrama + 1] = '2';
        switch (selE2.getSelectedIndex()) {
            //Apagado
            case 0:
                temp = 0;
                break;
            //bajo
            case 1:
                temp = 1;
                break;
            //Medio
            case 2:
                temp = 6;
                break;
            //Alto
            case 3:
                temp = 4;
                break;
        }
        trama[contTrama + 2] = (byte) ((temp) & 0x000000FF);
        //trama[contTrama + 2] = (byte)((selE2.getSelectedIndex()) & 0x000000FF);
        contTrama += 3;
    }

    if (jCheckAA.isSelected()) {
        trama[contTrama] = 'A';
        trama[contTrama + 1] = 'A';
        trama[contTrama + 2] = (byte) ((selAA.getSelectedIndex()) & 0x000000FF);
        contTrama += 3;
    }

    if (jCheckP1.isSelected()) {
        trama[contTrama] = 'P';
        trama[contTrama + 1] = '1';
        trama[contTrama + 2] = (byte) ((selP1.getSelectedIndex()) & 0x000000FF);
        contTrama += 3;
    }

    if (jCheckBX.isSelected()) {
        trama[contTrama] = 'B';
        trama[contTrama + 1] = 'X';
        trama[contTrama + 2] = (byte) (jSlider1.getValue() & 0x000000FF);
        contTrama += 3;
    }

    trama[contTrama] = 'M';
    trama[contTrama + 1] = 'R';
    try {
        puerto.EscribirPuerto(trama);
    } catch (IOException | PortInUseException ex) {
        Logger.getLogger(VentanaPruebas.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_jBEnviarActionPerformed

private void selE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selE2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_selE2ActionPerformed

private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
    jLabel9.setText(String.valueOf(jSlider1.getValue()));
}//GEN-LAST:event_jSlider1StateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        puerto.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPruebas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SelDestino;
    private javax.swing.JComboBox SelOrigen;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JCheckBox jCheckAA;
    private javax.swing.JCheckBox jCheckBX;
    private javax.swing.JCheckBox jCheckC1;
    private javax.swing.JCheckBox jCheckC2;
    private javax.swing.JCheckBox jCheckE1;
    private javax.swing.JCheckBox jCheckE2;
    private javax.swing.JCheckBox jCheckP1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextEstado;
    private javax.swing.JComboBox selAA;
    private javax.swing.JComboBox selC1;
    private javax.swing.JComboBox selC2;
    private javax.swing.JComboBox selE1;
    private javax.swing.JComboBox selE2;
    private javax.swing.JComboBox selP1;
    // End of variables declaration//GEN-END:variables
}
